kind = "web"
previewPath = "/"
title = "WaitLess - Gestion RDV & File d'attente"
version = "1.0.0"
id = "artifacts/rdv-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23449

[services.development]
run = "pnpm --filter @workspace/rdv-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rdv-app", "run", "build" ]
publicDir = "artifacts/rdv-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23449"
BASE_PATH = "/"
